/**
 * @name zodiaczvr tek
 * @author zodyvr
 * @authorId 309931975102300160
 * @authorLink ?
 * @version 1.2.1
 * @description A sleek, customizable Discord theme.
 * @updateUrl ?
 * @invite caAsUdtQbx
*/
@import url('https://fonts.googleapis.com/css2?family=Rajdhani');
@import url('https://patrykbielanin.github.io/discord-cyberpunk2077-theme/base.css');

/* I've commented most of these values so you can change them yourself. If you're having trouble, or you want to do more than what these values allow for, a volunteer might be able to help you in my server. */

.theme-dark {
/* Backdrop image which is shown behind the app. Can also be an HTML color. Falls back to accent color if invalid.
   To use an image from your computer, upload it somewhere first, copy its link, then paste it below. */
  --dplus-backdrop: url(https://i.imgur.com/3AiL3yN.png);

/* Accent color, used to decorate the UI with colors. */
  --dplus-accent-color-hue: 320;
  --dplus-accent-color-saturation: 60%;
  --dplus-accent-color-lightness: 31%;

/* Foreground color: For things like text and icons. */
  --dplus-foreground-color-hue-base: 210;
  --dplus-foreground-color-hue-links: 197;
  --dplus-foreground-color-saturation-amount: 1;
  --dplus-foreground-color-lightness-amount: 1;

/* Background color: Covers the backdrop so the app is easier to read. */
  --dplus-background-color-hue: 320;
  --dplus-background-color-saturation-amount: 1;
  --dplus-background-color-lightness-amount: 1;
  --dplus-background-color-alpha: 0.8;
}

/* If you use light theme, you can give it unique settings that are separate from dark theme. */
.theme-light {
  --dplus-backdrop: url(https://e0.pxfuel.com/wallpapers/655/830/desktop-wallpaper-cyberpunk-2077-yellow-plain-background.jpg);
  
  --dplus-accent-color-hue: 320;
  --dplus-accent-color-saturation: 60%;
  --dplus-accent-color-lightness: 31%;
  
  --dplus-foreground-color-hue-base: 210;
  --dplus-foreground-color-hue-links: 197;
  --dplus-foreground-color-saturation-amount: 1;
  --dplus-foreground-color-lightness-amount: 1;

  --dplus-background-color-hue: 320;
  --dplus-background-color-saturation-amount: 1;
  --dplus-background-color-lightness-amount: 1;
  --dplus-background-color-alpha: 0.8;
}

.theme-dark {
  --dplus-backdrop: url(https://cdn.discordapp.com/avatars/1053428061149876344/a8e10cc045450845b8a1e8d04510f1c5.webp?size=1024&width=0&height=256);
  
  --dplus-accent-color-hue: 320;
  --dplus-accent-color-saturation: 60%;
  --dplus-accent-color-lightness: 31%;
  
  --dplus-foreground-color-hue-base: 210;
  --dplus-foreground-color-hue-links: 197;
  --dplus-foreground-color-saturation-amount: 1;
  --dplus-foreground-color-lightness-amount: 1;

  --dplus-background-color-hue: 320;
  --dplus-background-color-saturation-amount: 1;
  --dplus-background-color-lightness-amount: 1;
  --dplus-background-color-alpha: 0.8;
}
